In [ ]:
pip install numpy

In [2]:
# Import statement for Numpy
import numpy as np
import sys

In [3]:
## Creating a sample vector in 1D
a = np.array([1,2,3])
a

array([1, 2, 3])

In [4]:
#Creating a sample vector in 2 D
b = np.array([[1,2,3],[2,4,5]])
b

array([[1, 2, 3],
       [2, 4, 5]])

In [5]:
# Creating a 2d vector with float types
c = np.array([[1.3,2.3,3.0],[4.0,5.0,6.0]])
c

array([[1.3, 2.3, 3. ],
       [4. , 5. , 6. ]])

In [6]:
## Get the dimension
print(a.ndim)
print(b.ndim)
print(c.ndim)

1
2
2


In [7]:
## Get the Shape
print(a.shape)
print(b.shape)
print(c.shape)

(3,)
(2, 3)
(2, 3)


In [8]:
## Get the data type
a.dtype

dtype('int32')

In [9]:
## if value is small, we can specifically chnage the dtype
d = np.array([1,2,3,4],dtype='int32')
d.dtype

dtype('int32')

In [10]:
## Get the Byte Size
#d.itemsize
print(c.itemsize)

8


In [129]:
 ## Get total size #both are similar; way of calculating is gvn below
print(d.size * d.itemsize)
print(d.nbytes)

16
16


In [12]:
## Part -2 -----------Accessing the arrays

In [13]:
a1 = np.array([[1,2,3,4,5,6,7],[8,9,7,6,5,4,3]])
a1

array([[1, 2, 3, 4, 5, 6, 7],
       [8, 9, 7, 6, 5, 4, 3]])

In [42]:
## Get a specific col [r,c]
a1[1,3]

6

In [43]:
a1[0,4]

5

In [55]:
## Get a specific row
a1[1,:]
#3 GEt a specific col
a1[:,3]

array([4, 6])

In [56]:
# Getting [ start index: end index: stp size]
a1[0,1:6:2]

array([2, 4, 6])

In [ ]:
## Initializng Different Types of Arrays

In [64]:
np.ones((4,2,2),dtype='int32') ## u can gv data type too

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [62]:
## all 0's matrix
np.zeros((2,2,3,4))

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])

In [67]:
np.full((2,2),99, dtype='float32') ## we can also specify data type wd dsss

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [71]:
## full_like
np.full_like(a1,4) ## or a1.shape 

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [73]:
## Random decimal numbers
np.random.rand(4,2) #or we can even declare as np.random.random_sample(a1.shape) ==> if you wanna reuse some shape already declared above

array([[0.31491702, 0.48358499],
       [0.18940597, 0.53797325],
       [0.80116189, 0.59012312],
       [0.32252001, 0.82958827]])

In [19]:
## suppose if you want all integers
np.random.randint(7,size=(3,3))

array([[0, 3, 5],
       [3, 4, 1],
       [1, 5, 3]])

In [20]:
np.random.randint(4,7,size=(3,3))

array([[5, 5, 5],
       [6, 5, 4],
       [4, 6, 6]])

In [21]:
np.random.randint(-4,8,size=(3,3))

array([[-1, -3, -4],
       [-2, -1, -1],
       [-3,  0,  5]])

In [22]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [30]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis =0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [68]:
## Define all ones
arr = np.full((5,5),1)
print(arr)

# 2. make a matirx just for the middle part
z = np.zeros((3,3))
z[1,1] = 9
z

## put the middle part to original place
arr[1:4,1:4] = z ## arr[1:-1,1:-1] can also be given
print(arr)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


# @@ Becareful while copying!!!! yy??? 

In [72]:
## Copying eg
a = np.array([1,2,3])
b = a
print(b)

## change something in b:
b[0] = 15
print(a)
print(b)
## we can see a's value also changed ## call by value takes place here in numpy hence we need to be carfeul to do a copy instead we should write as below::

a1 = np.array([2,3,4])
b1 = a1.copy()
b1[0] = 100
print(a1,b1) ## value gets retained...

[1 2 3]
[15  2  3]
[15  2  3]
[2 3 4] [100   3   4]


In [ ]:
############------------ Part 3 Mathematics

In [78]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [79]:
## unary operations:
a += 2 ## a+2
a

array([3, 4, 5, 6])

In [80]:
a-2

array([1, 2, 3, 4])

In [81]:
a * 2

array([ 6,  8, 10, 12])

In [82]:
a / 2

array([1.5, 2. , 2.5, 3. ])

In [83]:
## Binary Operations 
b = np.array([2,4,5,6])
a+b

array([ 5,  8, 10, 12])

In [84]:
a - b

array([1, 0, 0, 0])

In [85]:
## square 
a ** 2

array([ 9, 16, 25, 36], dtype=int32)

In [88]:
## Tangent Formula:
## to find sin(a)
np.sin(a)
## to find cos(A)
np.cos(a)

array([-0.9899925 , -0.65364362,  0.28366219,  0.96017029])

In [91]:
## Linear Algebra:
a = np.ones([2,3])
print(a)

b = np. full([3,2],3)
print(b)

## normal mul wont work since they are matrices
## To do matrix multiplcation: we need to import a method
val = np.matmul(a,b) ## To note, a's column and b's row shud be same no. here a = 2X3 and b = 3x2 ; hence 3
val

[[1. 1. 1.]
 [1. 1. 1.]]
[[3 3]
 [3 3]
 [3 3]]


array([[9., 9.],
       [9., 9.]])

@@Part 4 - Statistics - To find min,max,mean,etc.
    

In [95]:
stats = np.array([[1,2,3],[4,5,6]])

In [96]:
np.min(stats)

1

In [97]:
np.max(stats)

6

In [99]:
np.max(stats,axis = 0)

array([4, 5, 6])

In [100]:
np.sum(stats)

21

##@@ Pasrt 5 -Reorganizing arrays

In [101]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)
after = before.reshape(8,1)
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [102]:
## Verticall stacking vectors:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

## i need to stach v1 above v2 menas combine dese to single matrix

np.vstack([v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [109]:
## Horizonatal stack
h1 = np.ones((2,4))
h2 = np.full((2,2),3)

np.hstack((h1,h2))

array([[1., 1., 1., 1., 3., 3.],
       [1., 1., 1., 1., 3., 3.]])

@@Part6 - ## Miscellaneous Commands

In [120]:
## make sure each line has same no of data
filedata = np.genfromtxt('data.txt', delimiter=',')

## To convert file data type to Int from default "float"
filedata.astype('int32')

array([[ 1,  3,  4,  5,  6,  7,  8,  9],
       [12, 23, 34, 45, 67,  7,  8,  9],
       [ 1,  3,  4,  6,  4,  5, 67, 34]])

In [121]:
## Advanced Indexing and boolean masking:

In [123]:
filedata > 9

array([[False, False, False, False, False, False, False, False],
       [ True,  True,  True,  True,  True, False, False, False],
       [False, False, False, False, False, False,  True,  True]])

In [124]:
filedata[filedata > 20]

array([23., 34., 45., 67., 67., 34.])

In [125]:
## To find any value across a particular axis
np.any(filedata > 20,axis = 0)

array([False,  True,  True,  True,  True, False,  True,  True])

In [126]:
## combining 2 conditiosn
((filedata > 20) & (filedata < 40))

array([[False, False, False, False, False, False, False, False],
       [False,  True,  True, False, False, False, False, False],
       [False, False, False, False, False, False, False,  True]])

In [127]:
## not operator
(~(filedata > 20) & (filedata < 40))

array([[ True,  True,  True,  True,  True,  True,  True,  True],
       [ True, False, False, False, False,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True, False, False]])